HostelServiceTestApp/HostelService.WebUI/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HostelService.Domain.Abstract;
using HostelService.Domain.Entities;

namespace HostelService.WebUI.Controllers
{
    public class BookingController : Controller
    {
        private IRepository repository;

        public BookingController(IRepository repositoryParam) {
            this.repository = repositoryParam;
        }

        public ActionResult BookingLookup(int? customerId) {
            if (Session["UserType"].ToString() == "admin" |
                Convert.ToInt32(Session["UserID"]) == customerId) {                
                return View(repository.Bookings
                   .Where(p => p.CustomerID == customerId));                
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult BookingLookupAll() {
            if (Session["UserID"] != null) {
                if (Session["UserType"].ToString() == "admin") {
                    return View("BookingLookup", repository.Bookings);
                } else {
                    return RedirectToAction("CustomerLookup", "Customer");
                }
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        //Uses SearchBookingByCustomerId stored procedure
        [HttpPost]
        public ActionResult BookingLookup(string customerIdParam) {
            if (Session["UserID"] != null) {
                if (Session["UserType"].ToString() == "admin") {
                    if (!String.IsNullOrEmpty(customerIdParam)) {
                        //return View("BookingLookup", repository.Bookings
                            //.Where(p => p.CustomerID == Convert.ToInt32(customerIdParam)));
                        return View("BookingLookup", repository.SearchBookingByCustomerId(Convert.ToInt32(customerIdParam)));
                    } else {
                        return View("BookingLookup", repository.Bookings);
                    }
                } else {
                    return RedirectToAction("CustomerLookup", "Customer");
                }
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult BookingEdit(int? bookingIdParam) {
            if (Session["UserID"] != null) {
                if (Session["UserType"].ToString() == "admin") {
                    Booking bookingEdit = repository.Bookings
                        .FirstOrDefault(p => p.BookingID == bookingIdParam);
                    return View(bookingEdit);
                } else {
                    return RedirectToAction("CustomerLookup", "Customer");
                }
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }
        
        [HttpPost]
        public ActionResult BookingEdit(Booking bookingEdit) {
            if (Session["UserID"] != null) {
                if (Session["UserType"].ToString() == "admin") {
                    Customer customer = repository.Customers.FirstOrDefault(p => p.CustomerID == bookingEdit.CustomerID);
                    Card card = null;
                    if (bookingEdit.CardID != null) {
                        card = repository.Cards.FirstOrDefault(p => p.CardID == bookingEdit.CardID);
                    }
                    if (customer != null) {                        
                        if (ModelState.IsValid) {
                            if (card != null) {
                                if (card.CustomerID == customer.CustomerID) {
                                    repository.SaveBooking(bookingEdit);
                                    return RedirectToAction("CustomerLookup", "Customer");
                                } else {
                                    ModelState.AddModelError("", "Customer with ID=" + bookingEdit.CustomerID +
                                        " has not card with ID=" + bookingEdit.CardID);
                                }
                            } else {
                                if (bookingEdit.CardID == null) {
                                    repository.SaveBooking(bookingEdit);
                                    return RedirectToAction("CustomerLookup", "Customer");
                                } else {
                                    ModelState.AddModelError("", "Card with ID=" + bookingEdit.CardID + " does not exists");
                                }
                            }
                        } else {
                            ModelState.AddModelError("", "Model is not valid");
                        }                       
                    } else {
                        ModelState.AddModelError("", "Customer with id=" + bookingEdit.CustomerID +
                            " does not exists");
                    }                    
                }
                return View(bookingEdit);
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }        

        public ActionResult BookingCreate() {
            return View("BookingEdit", new Booking());
        }

        public ActionResult BookingDelete(string bookIdStr) {
            if (Session["UserType"].ToString() == "admin") {
                int bookId = Convert.ToInt32(bookIdStr); 
                repository.DeleteCard(bookId);
                return RedirectToAction("CustomerLookup", "Customer");
            } else if (Session["UserType"].ToString() == "customer") {
                return RedirectToAction("CustomerLookup", "Customer");
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

    }
}

HostelServiceTestApp/HostelService.WebUI/Views/Booking/BookingEdit.cshtml
@model HostelService.Domain.Entities.Booking

@{
    ViewBag.Title = "BookingEdit";
}

<h2>BookingEdit</h2>

@using (Html.BeginForm("BookingEdit", "Booking")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.BookingID)

        <div class="form-group">
            @Html.LabelFor(model => model.CardID, "CardID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CBBookingID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CBBookingID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CBBookingID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, "CustomerID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalCustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocalCustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocalCustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SiteID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BookingDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BookingDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BookingDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstNightDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstNightDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstNightDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfDays, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfDays, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfDays, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPersons, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPersons, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPersons, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeOfRoom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TypeOfRoom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TypeOfRoom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "CustomerLookup", "Customer", null, new { @class = "btn btn-default" })
</div>

HostelServiceTestApp/HostelService.WebUI/Views/Booking/BookingLookup.cshtml
@model IEnumerable<HostelService.Domain.Entities.Booking>

@{
    ViewBag.Title = "BookingLookup";
}

<h2>BookingLookup</h2>

@using (Html.BeginForm("BookingLookup", "Booking")) {
    if (Session["UserType"].ToString() == "admin") {
        <p>
            @Html.TextBox("customerIdParam")
            <input type="submit" value="Search by CustomerID" /> 
        </p>
    }
}

@if (Session["UserType"].ToString() == "admin") {
    <p>
        @Html.ActionLink("Load All Bookings", "BookingLookupAll", "Booking", null, new { @class = "btn btn-default" })
    </p>
}

@if (Session["UserType"].ToString() == "admin") {
    <p>
        @Html.ActionLink("Create new", "BookingCreate", "Booking", null, new { @class = "btn btn-primary" })
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.BookingID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Card.CardNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CBBookingID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Customer.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocalCustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiteID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BookingDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FirstNightDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfDays)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumberOfPersons)
        </th>                       
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TypeOfRoom)
        </th>
        <th></th>
        <th></th>        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.BookingID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Card.CardNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CBBookingID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Customer.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocalCustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SiteID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BookingDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FirstNightDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfDays)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfPersons)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfRoom)
        </td>
        <td>
            @if (Session["UserType"].ToString() == "admin") {
                @Html.ActionLink("Edit", "BookingEdit", "Booking", new { bookingIdParam = item.BookingID }, new { @class = "btn btn-default" })
            }            
        </td>
        <td>
            @if (Session["UserType"].ToString() == "admin") {
                @Html.ActionLink("Delete", "BookingDelete", "Booking", new { bookIdStr = Convert.ToString(item.BookingID) }, new { @class = "btn btn-default" })
            }
            
        </td>
    </tr>
}

</table>

@Html.ActionLink("Back to CustomerLookup", "CustomerLookup", "Customer", null, new { @class = "btn btn-default" })