HostelServiceTestApp/HostelService.WebUI/Controllers/CardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HostelService.Domain.Abstract;
using HostelService.Domain.Entities;

namespace HostelService.WebUI.Controllers {
    public class CardController : Controller {
        private IRepository repository;

        public CardController(IRepository repositoryParam) {
            this.repository = repositoryParam;
        }

        public ActionResult CardLookup(int? customerId) {
            if (Session["UserID"] != null) {
                if (Convert.ToInt32(Session["UserID"]) == customerId
                    | Session["UserType"].ToString() == "admin") {
                    Card someCard = repository.Cards
                        .FirstOrDefault(p => p.CustomerID == customerId);
                    if (someCard != null) {                        
                        return View(repository.Cards
                            .Where(p => p.CustomerID == customerId));
                    } else {
                        return View(new List<Card>());
                    }
                } else {
                    return RedirectToAction("CustomerLookup", "Customer");
                }
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult CardLookupAll() {
            if (Session["UserID"] != null) {
                if (Session["UserType"].ToString() == "admin") {
                    return View("CardLookup", repository.Cards);
                } else {
                    return RedirectToAction("CustomerLookup", "Customer");
                }
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        [HttpPost]
        public ActionResult CardLookup(string customerIdParam) {
            if (Session["UserType"].ToString() == "admin") {                
                if (!String.IsNullOrEmpty(customerIdParam)) {
                    return View("CardLookup", repository.Cards
                        .Where(p => p.CustomerID == Convert.ToInt32(customerIdParam)));
                } else {
                    return View("CardLookup", repository.Cards);
                }                
            } else if (Session["UserType"].ToString() == "customer") {
                return RedirectToAction("CustomerLookup", "Customer");
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult CardEdit(int? cardId) {
            if (Session["UserType"].ToString() == "admin") {
                Card cardEdit = repository.Cards
                    .FirstOrDefault(p => p.CardID == cardId);
                return View(cardEdit);
            } else if (Session["UserType"].ToString() == "customer") {
                return RedirectToAction("CustomerLookup", "Customer");
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        [HttpPost]
        public ActionResult CardEdit(Card card) {
            if (Session["UserType"].ToString() == "admin") {
                Customer customer = repository.Customers
                    .FirstOrDefault(p => p.CustomerID == card.CustomerID);
                if (customer != null) {
                    if (ModelState.IsValid) {                        
                        repository.SaveCard(card);
                        return RedirectToAction("CustomerLookup", "Customer");
                    } else {
                        ModelState.AddModelError("", "Model is not valid");
                    }
                } else {
                    ModelState.AddModelError("", "Customer with id=" + card.CustomerID + " does not exists");
                }
                return View(card);                    
            } else if (Session["UserType"].ToString() == "customer") {
                return RedirectToAction("CustomerLookup", "Customer");
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }

        public ActionResult CardCreate() {
            if (Session["UserType"].ToString() == "admin") {
                return View("CardEdit", new Card());
            } else if (Session["UserType"].ToString() == "customer") {
                return RedirectToAction("CustomerLookup", "Customer");
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }
        
        public ActionResult CardDelete(string cardIdStr) {
            if (Session["UserType"].ToString() == "admin") {
                int cardId = Convert.ToInt32(cardIdStr);
                IEnumerable<Booking> bookings =
                    repository.Bookings.Where(p => p.CardID == cardId);
                foreach (Booking book in bookings) {
                    Booking forEd = new Booking();
                    forEd = book;
                    forEd.CardID = null;
                    repository.SaveBooking(forEd);
                }
                repository.DeleteCard(cardId);
                return RedirectToAction("CustomerLookup", "Customer");
            } else if (Session["UserType"].ToString() == "customer") {
                return RedirectToAction("CustomerLookup", "Customer");
            } else {
                return RedirectToAction("Login", "Admin");
            }
        }
    }
}

HostelServiceTestApp/HostelService.WebUI/Views/Card/CardEdit.cshtml
@model HostelService.Domain.Entities.Card

@{
    ViewBag.Title = "CardEdit";
}

<h2>CardEdit</h2>

@using (Html.BeginForm("CardEdit", "Card")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.CardID)

        <div class="form-group">
            @Html.LabelFor(model => model.SiteID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SiteID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SiteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LocalCustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LocalCustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LocalCustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IssueDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IssueDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IssueDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ExpirationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ExpirationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ExpirationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthYear, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.PermissionStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.PermissionStatus)
                    @Html.ValidationMessageFor(model => model.PermissionStatus, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Cancel", "CustomerLookup", "Customer", null, new { @class = "btn btn-default" })
</div>

HostelServiceTestApp/HostelService.WebUI/Views/Card/CardLookup.cshtml
@model IEnumerable<HostelService.Domain.Entities.Card>

@{
    ViewBag.Title = "CardLookup";
}

<h2>CardLookup</h2>

@using (Html.BeginForm("CardLookup", "Card")) {
    if (Session["UserType"].ToString() == "admin") {
        <p>
            @Html.TextBox("customerIdParam")
            <input type="submit" value="Search by CustomerID" />  
        </p>      
    }
}

@if (Session["UserType"].ToString() == "admin") {
    <p>
        @Html.ActionLink("Load all cards", "CardLookupAll", "Card", null, new { @class = "btn btn-default" })
    </p>
}

@if (Session["UserType"].ToString() == "admin") {
    <p>
        @Html.ActionLink("Create new", "CardCreate", "Card", null, new { @class = "btn btn-primary" })
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CardID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SiteID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LocalCustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CardNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CustomerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IssueDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ExpirationDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthYear)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mobile)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PermissionStatus)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CardID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SiteID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocalCustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CardNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CustomerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IssueDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ExpirationDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthYear)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Mobile)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PermissionStatus)
        </td>
        <td>
            @if (Session["UserType"].ToString() == "admin") { 
                @Html.ActionLink("Edit", "CardEdit", "Card", new { cardId = item.CardID }, new { @class = "btn btn-default" })                
            }
        </td>
        <td>
            @if (Session["UserType"].ToString() == "admin") {
                @Html.ActionLink("Delete", "CardDelete", "Card", new { cardIdStr = Convert.ToString(item.CardID) }, new { @class = "btn btn-default" })
            }
        </td>
    </tr>
}

</table>

@Html.ActionLink("Back to CustomerLookup", "CustomerLookup", "Customer", null, new { @class = "btn btn-default" });